### ISSUE TITLE
embedded items are bugging after you identify once

### ISSUE THREAD

**Issue by ultrakorne** [Forien/foundryvtt-forien-unidentified-items#22]
**Module Version:** v0.2.3

**Describe the bug**
embedded items are bugging after you mistify, identify once

**To Reproduce**
have an item in an actor.
mistify it
identify it.
the incorrect options in the item tab bar will show (peek when the item is already revealed, see screenshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/2083769/90989213-4181bd00-e599-11ea-93bf-02ac1f33fb44.png)

**Browser:**
native client

**Foundry Version:** 
0.6.5
**Game System:**

**Comment by Forien** [comment]
https://gyazo.com/013226cf61758a913dd712755ecf348e

I can't reproduce the issue. I mean, I am aware of header buttons not re-rendering unless you close/open the Item Sheet, but that's Foundry issue. I might still do some hacking around to fix that, but I never considered it such an issue.

But item itself is properly getting mystified/identified inside Actor, and after reopening sheet proper buttons show.

If your issue is more than just about the header buttons, please provide more information :)
