### ISSUE TITLE
[BUG] Can't mystify item from Actor's inventory and from within Compendium.

### ISSUE THREAD

**Issue by Hydroxi** [Forien/foundryvtt-forien-unidentified-items#3]
Hi,

when mystifying an exisiting item on a tidy5e sheet i get the following js error and nothing else happens.
Mystifying in the sidebar an dragging the item to the character works as intended.

`TypeError: origData is null Identification.js:13:7`

**Comment by Forien** [comment]
I've just installed Tidy5e Sheet and it appears to be working.

may I ask for more information? What browser are you using, what other modules etc?

Also, are you using v0.1.3 of this module?

**Comment by schultzcole** [comment]
This issue does not seem to be unique to Tidy5e sheet. For me, trying to "Mystify" any embedded equipment throws an error:
![mystify_empedded_item](https://user-images.githubusercontent.com/1226888/85900255-237c2400-b7c5-11ea-8e64-779223f67f47.png)

Repro steps:
1. Create new actor (core dnd5e sheet)
2. On the inventory tab, add a new item by clicking the "+Add" button in one of the section headers.
3. Open the item and click "Mystify".
4. Nothing happens, and the above error is posted to console.

This also happens with items dragged from Compendia or from the Items tab in the sidebar.

Notably, an item that was previously unidentified, then added to the character sheet, then identified, does not have the button to mystify the item when opened from the character sheet, whereas newly added normal items do have the button to mystify when opened from the character sheet.

**Comment by Forien** [comment]
> Notably, an item that was previously unidentified, then added to the character sheet, then identified, does not have the button to mystify the item when opened from the character sheet, whereas newly added normal items do have the button to mystify when opened from the character sheet.

that is probably due to `header buttons` not being re-rendered on item update. When you close item and open it again, button should show.

## **As for main issue**  
Ok, I got it now. I completely misunderstood what you originally mean, sorry for that. So you cannot mystify items owned by Actors or items inside compendium. You can only mystify items in World (sidebar).   
To be honest, I never intended to allow mystifying embedded items, although I might just add that, why not. 

So, right now make sure you have item imported into a world (in sidebar) before mystifying, in next update I will add option (or "fix" rather) to mystify from actor/compendium.

**Comment by Forien** [comment]
Fixed in _**v0.1.5**_.

Option to "replace with mystified item" will come in future update. Closing issue.
